---

- hosts: servers
  remote_user: root
  gather_facts: false
  tasks:
    - block:
      - debug: msg="Parsed acl_rule_nums {{acl_rule_nums}}"

      - set_fact: index_pj={{index}}

      - set_fact:
          lb_name: "lb-{{index_pj}}-0"
          project_name: "proj-perf-{{index_pj}}"
          acl_group_name: "acl_group-{{index_pj}}-0-0"
          acl_rule_prefix: "acl_rule-{{index_pj}}-0"

      - name: get {{project_name}} id
        shell: |
          source {{ openrc }} && openstack project show {{ project_name }} --format value --column id
        register: project_id

      - name: create acl_group
        shell: |
          source {{openrc}}
          set -e
          /tmp/wait-for-lb-done.sh {{lb_name}}
          exists=`/tmp/if-exists-resource.sh acl_groups {{ acl_group_name }}`
          if [ "$exists" = "false" ]; then
            neutron --os-project-id {{project_id.stdout}} lbaas-acl-group-create RegionOne \ 
            --name {{acl_group_name}} --tenant-id {{project_id.stdout}}
          fi
        tags: acl_group
        register: result

      - name: create acl_rule
        shell: |
          source {{openrc}}
          set -e
          /tmp/wait-for-lb-done.sh {{lb_name}}
          neutron --os-project-id {{project_id.stdout}} lbaas-acl-rule-create {{acl_group_name}} \
            --ip-address 11.11.{{ipC}}.{{ipD}} --tenant-id {{project_id.stdout}}
        with_items: "{{range(0, acl_rule_nums|int, 1) | list}}"
        loop_control:
          label: "{{ rule_name }} delta:{{ result.delta | default('0:00:00.000') }}"
        tags: acl_rule
        vars:
          ipC: "{{ (item / 254) | int }}"
          ipD: "{{ item % 254 }}"
          rule_name: "{{acl_rule_prefix}}-{{item}}"
        register: result

      - name: delete acl_group
        shell: |
          source {{openrc}}
          set -e
          /tmp/wait-for-lb-done.sh {{lb_name}}
          exists=`/tmp/if-exists-resource.sh acl_groups {{ acl_group_name }}`
          if [ "$exists" = "true" ]; then
            neutron --os-project-id {{project_id.stdout}} lbaas-acl-group-delete {{acl_group_name}} \
            --tenant-id {{project_id.stdout}}          
          fi
        tags: acl_group
        register: result

      environment:
        NEUTRONDB_HOSTNAME: "{{ neutrondb_hostname }}"
        NEUTRONDB_PASSWORD: "{{ neutrondb_password }}"
        NEUTRONDB_DATABASE: "{{ neutrondb_database }}"
