---

- hosts: servers
  remote_user: root
  gather_facts: false
  tasks:
    - block:
      - set_fact:
          l7policy_num: "{{l7policy_num}}"
          lb_name: lb-0-0

      - name: delete l7policy
        shell: |
          source {{openrc}}
          set -e
          /tmp/wait-for-lb-done.sh {{lb_name}}
          exists=`/tmp/if-exists-resource.sh l7policies {{ policy_name }}`
          if [ "$exists" = "true" ]; then
            neutron lbaas-l7policy-delete {{policy_name}}
          fi
        loop: "{{range(0, l7policy_num|int, 1) | list}}"
        loop_control:
          label: "delete {{policy_name}} success"
        vars:
          policy_name: l7policy-0-0-{{item}}

  environment:
    NEUTRONDB_HOSTNAME: "{{ neutrondb_hostname }}"
    NEUTRONDB_PASSWORD: "{{ neutrondb_password }}"
    NEUTRONDB_DATABASE: "{{ neutrondb_database }}"
